# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioptim
channels:
- conda-forge
dependencies:
- biorbd >=1.9.9
- bioviz
- python-graphviz
- pyqtgraph
- gitpython
